[package]
name = "rmdupes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
walkdir = "2"
blake3 = "0.3.8"
